workspace:
  base: /go
  path: src/github.com/magicalbanana/rmq

pipeline:
  notify_start:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: ci
    username: drone
    template: "<{{ build.link }}|Build #{{ build.number }} started> on <http://github.com/{{ repo.owner }}/{{ repo.name }}/tree/{{ build.branch }}|{{ repo.name }}:{{ build.branch }}> by @{{ build.author }}"

  build:
    image: golang:1.9-alpine
    commands:
      - go build ./...

  autotag:
    image: golang:1.9-alpine
    commands:
      - apk update && apk add make git
      - git clone https://github.com/pantheon-systems/autotag.git
      - cd autotag
      - go get -u github.com/pantheon-systems/autotag/autotag
      - make deps build && mv autotag ../ && cd ..
      - rm -rf autotag/
      - autotag

    when:
      # event: push
      # branch: master

  notify_finish:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: ci
    username: drone
    template: "<{{ build.link }}|Build #{{ build.number }} {{ build.status }}> on <http://github.com/{{ repo.owner }}/{{ repo.name }}/tree/{{ build.branch }}|{{ repo.name }}:{{ build.branch }}> by @{{ build.author }}"
    when:
      status: [ success, failure ]

